### ISSUE TITLE
[snitch] Streaming registers producing incorrect results in `frep.o`

### ISSUE THREAD

**Issue by zero9178** [gvsoc/gvsoc#32]
See following example program compiled with the snitch runtime:
```c
#include <alloc_decls.h>
#include <team_decls.h>

void kernel(double* lhs, double* rhs, double* result);

asm(".text\n"
    ".globl kernel\n"
    ".p2align 2\n"
    "kernel:\n"
    "    mv t2, a0\n"
    "    mv t1, a1\n"
    "    mv t0, a2\n"
    "    li t3, 8\n"
    "    li t4, 127\n"
    "    scfgwi t4, 95\n"
    "    scfgwi t3, 223\n"
    "    scfgwi t2, 768\n"
    "    scfgwi t1, 769\n"
    "    scfgwi t0, 898\n"
    "    csrrsi zero, 1984, 1\n"
    "    li t0, 3\n"
    "    frep.o t0, 1, 0, 0\n"
    "    fadd.d ft2, ft0, ft1\n"
    "    csrrci zero, 1984, 1\n"
    "    ret");

int main() {
    if (snrt_cluster_core_idx() != 0) return 0;

    double* a = snrt_l1_next();
    for (int i = 0; i < 4; i++) {
        a[i] = i + 1;
    }

    double* b = a + 4;
    kernel(a, a, b);

    int error = 0;
    for (int i = 0; i < 4; i++) {
        if (b[i] != 2 * (i + 1)) error++;
    }

    return error;
}
```
When run with verilator the program correctly exits with exit code 0 and separately dumping reveals that the program functions as expected (just adding `a` to itself and storing the result in `b`).

When run with gvsoc (`gvsoc --target pulp.snitch.snitch_cluster_single --binary snitch_cluster/target/snitch_cluster/sw/tests/build/simple.elf run`) all results past the first element are incorrect leading to an exit code of 3. Looking at the instruction trace shows:
```
17920000: 896: [/soc/pe0/insn                                              ] kernel:0                         M 800001d4 addi                t2, a0, 0         t2=10000000  a0:10000000 
17940000: 897: [/soc/pe0/insn                                              ] kernel:0                         M 800001d8 addi                t1, a1, 0         t1=10000000  a1:10000000 
17960000: 898: [/soc/pe0/insn                                              ] kernel:0                         M 800001dc addi                t0, a2, 0         t0=10000020  a2:10000020 
17980000: 899: [/soc/pe0/insn                                              ] kernel:0                         M 800001e0 addi                t3, 0, 8          t3=00000008 
18000000: 900: [/soc/pe0/insn                                              ] kernel:0                         M 800001e4 addi                t4, 0, 127        t4=0000007f 
18020000: 901: [/soc/fp_ss0/insn                                           ] kernel:0                         M 800001e8 scfgwi              t4, 0x1f, 0x2     t4:0000007f 
18040000: 902: [/soc/fp_ss0/insn                                           ] kernel:0                         M 800001ec scfgwi              t3, 0x1f, 0x6     t3:00000008 
18060000: 903: [/soc/fp_ss0/insn                                           ] kernel:0                         M 800001f0 scfgwi              t2, 0x0, 0x18     t2:10000000 
18080000: 904: [/soc/fp_ss0/insn                                           ] kernel:0                         M 800001f4 scfgwi              t1, 0x1, 0x18     t1:10000000 
18100000: 905: [/soc/fp_ss0/insn                                           ] kernel:0                         M 800001f8 scfgwi              t0, 0x2, 0x1c     t0:10000020 
18120000: 906: [/soc/pe0/insn                                              ] kernel:0                         M 800001fc csrrsi              0, 0x1,  �_   
18120000: 906: [/soc/fp_ss0/insn                                           ] kernel:0                         M 800001fc csrrsi              0, 0x1,  �_   
18140000: 907: [/soc/pe0/insn                                              ] kernel:0                         M 80000200 addi                t0, 0, 3          t0=00000003 
18160000: 908: [/soc/pe0/insn                                              ] kernel:0                         M 80000204 frep.o              0x0, 0x0, t0, 0x0  t0:00000003 
18260000: 913: [/soc/fp_ss0/insn                                           ] kernel:0                         M 80000208 fadd.d              f2, f0, f1, 0x7   f2=4000000000000000  f0:3ff0000000000000  f1:3ff0000000000000 
18300000: 915: [/soc/fp_ss0/insn                                           ] kernel:0                         M 80000208 fadd.d              f2, f0, f1, 0x7   f2=4000000000000000  f0:3ff0000000000000  f1:3ff0000000000000 
18320000: 916: [/soc/fp_ss0/insn                                           ] kernel:0                         M 80000208 fadd.d              f2, f0, f1, 0x7   f2=4000000000000000  f0:3ff0000000000000  f1:3ff0000000000000 
18360000: 918: [/soc/fp_ss0/insn                                           ] kernel:0                         M 80000208 fadd.d              f2, f0, f1, 0x7   f2=4000000000000000  f0:3ff0000000000000  f1:3ff0000000000000 
18400000: 920: [/soc/pe0/insn                                              ] kernel:0                         M 8000020c csrrci              0, 0x1,  �_    
18400000: 920: [/soc/fp_ss0/insn                                           ] kernel:0                         M 8000020c csrrci              0, 0x1,  �_   
18420000: 921: [/soc/pe0/insn                                              ] kernel:0                         M 80000210 jalr                0, ra, 0           ra:80000294
```
As the operands to the `fadd.d` seemingly never change, it seems as if the streaming registers within the `frep.o` are not being advanced to the next element in the input stream.

Tested at SHA 558704fed8aa59c0876f0479194db0e4a282088f

**Comment by haugoug** [comment]
It seems the model gets an invalid ssr ID:
26140000: 1307: [/soc/fp_ss0/ssr                                            ] Invalid configuration data mover
I'm not very familiar with snitch, looking at the specs, I see the first 5 bits of the immediate encodes the SSR ID, which in your case is equal to 0x1f. Does this value has a particular meaning on snitch ?

**Comment by zero9178** [comment]
> It seems the model gets an invalid ssr ID: 26140000: 1307: [/soc/fp_ss0/ssr ] Invalid configuration data mover I'm not very familiar with snitch, looking at the specs, I see the first 5 bits of the immediate encodes the SSR ID, which in your case is equal to 0x1f. Does this value has a particular meaning on snitch ?

Thanks for taking a look! Running the code with `./install/bin/gvsoc --target pulp.snitch.snitch_cluster_single run --binary /home/markus/CLionProjects/snitch_cluster/target/snitch_cluster/sw/tests/build/simple.elf --trace=ssr` sadly did not yield me the same output, so I am assuming this is in your current working tree?

Either way, the `0x1f` is a special sentinel value that encodes that the given  configuration should be written to all data movers. 
This can be nicely seen in the snitch runtime e.g:
https://github.com/pulp-platform/snitch_cluster/blob/main/sw/snRuntime/src/ssr.h#L16-L23
The first two `scfgwi` that use `0x1f` in particular encode the bounds and stride of the data movers.

**Comment by haugoug** [comment]
It seems this test is not using ssr, I've tried with the code you provided and I also enabled full traces with these options:
--trace=pe0 --trace=fp_ss0 --trace-level=trace
I've pushed a fix to write all 3 ssr when this special value is seen.
The fix has just been merged, let me know.

**Comment by zero9178** [comment]
> It seems this test is not using ssr, I've tried with the code you provided and I also enabled full traces with these options: --trace=pe0 --trace=fp_ss0 --trace-level=trace I've pushed a fix to write all 3 ssr when this special value is seen. The fix has just been merged, let me know.

Sorry, the `simple.elf` was the dummy file where I copy pasted the above program into :sweat_smile: 
Anyways, I just tested current HEAD and it is indeed fixed thank you!
