### ISSUE TITLE
Need for riscv-gnu-toolchain?

### ISSUE THREAD

**Issue by andrelhgama** [gvsoc/gvsoc#65]
I followed the steps in the readme to install gvsoc on my machine, but when I ran "make all" I got "invalid target specified: rv32". I reinstalled all the pip3 core and gapy requirements, with and without sudo but nothing fixed it. Does that mean that I need a riscv-gnu-toolchain?

Edit: Something had gone wrong while updating the submodules, I suppose, because a clone in a different directory made it work past this point. So as a change to the question:
To run Tutorial 0_how_to_build_a_system_from_scratch, `riscv64-unknown-elf-gcc` is needed. Therefore, is it correct to say that I need to install the `riscv-gnu-toolchain` for that?

**Comment by haugoug** [comment]
There was an issue some times ago where the error was not properly reported when a dependency was issing, leading to such an error.
Have you tried with the latest version from main branch ?

**Comment by andrelhgama** [comment]
Yes, I was trying with the main version from the main branch.
As I edited the post, I have installed the `riscv-gnu-toolchain` both for 64 and 32 bit versions to be able to run the tutorials. I managed to run them with the 64 bit version. What are the changes I need to make to run with the 32 bit version?

**Comment by andrelhgama** [comment]
Overall, I learned that the `riscv-gnu-toolchain` is necessary to `make gvsoc` and the compiled 64-bit version is necessary for the tutorials. It is probably possible to modify the tutorials to run with the 32-bit version, but I wasn't successful.
